// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query/query.proto

package query

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SimpleQuery struct {
	Index                int32    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleQuery) Reset()         { *m = SimpleQuery{} }
func (m *SimpleQuery) String() string { return proto.CompactTextString(m) }
func (*SimpleQuery) ProtoMessage()    {}
func (*SimpleQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{0}
}

func (m *SimpleQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleQuery.Unmarshal(m, b)
}
func (m *SimpleQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleQuery.Marshal(b, m, deterministic)
}
func (m *SimpleQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleQuery.Merge(m, src)
}
func (m *SimpleQuery) XXX_Size() int {
	return xxx_messageInfo_SimpleQuery.Size(m)
}
func (m *SimpleQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleQuery proto.InternalMessageInfo

func (m *SimpleQuery) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type QueryResponse struct {
	Value                int32    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{1}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type CuckooBucketQuery struct {
	BucketId             uint64   `protobuf:"varint,1,opt,name=BucketId,proto3" json:"BucketId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CuckooBucketQuery) Reset()         { *m = CuckooBucketQuery{} }
func (m *CuckooBucketQuery) String() string { return proto.CompactTextString(m) }
func (*CuckooBucketQuery) ProtoMessage()    {}
func (*CuckooBucketQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{2}
}

func (m *CuckooBucketQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CuckooBucketQuery.Unmarshal(m, b)
}
func (m *CuckooBucketQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CuckooBucketQuery.Marshal(b, m, deterministic)
}
func (m *CuckooBucketQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CuckooBucketQuery.Merge(m, src)
}
func (m *CuckooBucketQuery) XXX_Size() int {
	return xxx_messageInfo_CuckooBucketQuery.Size(m)
}
func (m *CuckooBucketQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_CuckooBucketQuery.DiscardUnknown(m)
}

var xxx_messageInfo_CuckooBucketQuery proto.InternalMessageInfo

func (m *CuckooBucketQuery) GetBucketId() uint64 {
	if m != nil {
		return m.BucketId
	}
	return 0
}

type CuckooBucketResponse struct {
	Bucket               []uint64 `protobuf:"varint,1,rep,packed,name=Bucket,proto3" json:"Bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CuckooBucketResponse) Reset()         { *m = CuckooBucketResponse{} }
func (m *CuckooBucketResponse) String() string { return proto.CompactTextString(m) }
func (*CuckooBucketResponse) ProtoMessage()    {}
func (*CuckooBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{3}
}

func (m *CuckooBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CuckooBucketResponse.Unmarshal(m, b)
}
func (m *CuckooBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CuckooBucketResponse.Marshal(b, m, deterministic)
}
func (m *CuckooBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CuckooBucketResponse.Merge(m, src)
}
func (m *CuckooBucketResponse) XXX_Size() int {
	return xxx_messageInfo_CuckooBucketResponse.Size(m)
}
func (m *CuckooBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CuckooBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CuckooBucketResponse proto.InternalMessageInfo

func (m *CuckooBucketResponse) GetBucket() []uint64 {
	if m != nil {
		return m.Bucket
	}
	return nil
}

type HashTableInfoQuery struct {
	Dummy                uint64   `protobuf:"varint,1,opt,name=Dummy,proto3" json:"Dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashTableInfoQuery) Reset()         { *m = HashTableInfoQuery{} }
func (m *HashTableInfoQuery) String() string { return proto.CompactTextString(m) }
func (*HashTableInfoQuery) ProtoMessage()    {}
func (*HashTableInfoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{4}
}

func (m *HashTableInfoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashTableInfoQuery.Unmarshal(m, b)
}
func (m *HashTableInfoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashTableInfoQuery.Marshal(b, m, deterministic)
}
func (m *HashTableInfoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashTableInfoQuery.Merge(m, src)
}
func (m *HashTableInfoQuery) XXX_Size() int {
	return xxx_messageInfo_HashTableInfoQuery.Size(m)
}
func (m *HashTableInfoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_HashTableInfoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_HashTableInfoQuery proto.InternalMessageInfo

func (m *HashTableInfoQuery) GetDummy() uint64 {
	if m != nil {
		return m.Dummy
	}
	return 0
}

type HashTableInfoResponse struct {
	Size                 uint64   `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Load                 uint64   `protobuf:"varint,2,opt,name=Load,proto3" json:"Load,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashTableInfoResponse) Reset()         { *m = HashTableInfoResponse{} }
func (m *HashTableInfoResponse) String() string { return proto.CompactTextString(m) }
func (*HashTableInfoResponse) ProtoMessage()    {}
func (*HashTableInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5d1f792f5992be, []int{5}
}

func (m *HashTableInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashTableInfoResponse.Unmarshal(m, b)
}
func (m *HashTableInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashTableInfoResponse.Marshal(b, m, deterministic)
}
func (m *HashTableInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashTableInfoResponse.Merge(m, src)
}
func (m *HashTableInfoResponse) XXX_Size() int {
	return xxx_messageInfo_HashTableInfoResponse.Size(m)
}
func (m *HashTableInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashTableInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashTableInfoResponse proto.InternalMessageInfo

func (m *HashTableInfoResponse) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *HashTableInfoResponse) GetLoad() uint64 {
	if m != nil {
		return m.Load
	}
	return 0
}

func init() {
	proto.RegisterType((*SimpleQuery)(nil), "query.SimpleQuery")
	proto.RegisterType((*QueryResponse)(nil), "query.QueryResponse")
	proto.RegisterType((*CuckooBucketQuery)(nil), "query.CuckooBucketQuery")
	proto.RegisterType((*CuckooBucketResponse)(nil), "query.CuckooBucketResponse")
	proto.RegisterType((*HashTableInfoQuery)(nil), "query.HashTableInfoQuery")
	proto.RegisterType((*HashTableInfoResponse)(nil), "query.HashTableInfoResponse")
}

func init() { proto.RegisterFile("query/query.proto", fileDescriptor_bf5d1f792f5992be) }

var fileDescriptor_bf5d1f792f5992be = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x8d, 0x6e, 0x43, 0x9e, 0x8a, 0x2e, 0x4e, 0xa9, 0xd3, 0xc3, 0x88, 0x08, 0xc3, 0x43,
	0x27, 0xfa, 0x07, 0x08, 0x9b, 0xa8, 0x05, 0x15, 0x6c, 0xc5, 0x83, 0xb7, 0xae, 0x7d, 0x6a, 0x59,
	0x9b, 0xd4, 0xb6, 0x91, 0xcd, 0xff, 0xdb, 0xbb, 0x24, 0x69, 0xab, 0x63, 0xbb, 0x79, 0x29, 0xf9,
	0xbd, 0xf7, 0xe5, 0x4b, 0xdf, 0xc7, 0x83, 0xf6, 0x87, 0xc4, 0x6c, 0x36, 0xd0, 0x5f, 0x3b, 0xcd,
	0x44, 0x21, 0x68, 0x53, 0x03, 0x3b, 0x86, 0x0d, 0x2f, 0x4a, 0xd2, 0x18, 0x1f, 0x15, 0xd2, 0x0e,
	0x34, 0x1d, 0x1e, 0xe2, 0xd4, 0x22, 0x3d, 0xd2, 0x6f, 0xba, 0x06, 0xd8, 0x09, 0x6c, 0xe9, 0xb6,
	0x8b, 0x79, 0x2a, 0x78, 0x8e, 0x4a, 0xf6, 0xec, 0xc7, 0x12, 0x2b, 0x99, 0x06, 0x36, 0x80, 0xf6,
	0x48, 0x06, 0x13, 0x21, 0x86, 0x32, 0x98, 0x60, 0x61, 0x1c, 0xbb, 0xb0, 0x6e, 0xd0, 0x09, 0xb5,
	0xba, 0xe1, 0xd6, 0xcc, 0x6c, 0xe8, 0xfc, 0xbd, 0x50, 0xdb, 0xef, 0x43, 0xcb, 0x54, 0x2c, 0xd2,
	0x5b, 0xeb, 0x37, 0xdc, 0x92, 0xd8, 0x29, 0xd0, 0x5b, 0x3f, 0x7f, 0x7f, 0xf2, 0xc7, 0x31, 0x3a,
	0xfc, 0x55, 0xd4, 0xff, 0x7c, 0x25, 0x93, 0x64, 0x56, 0xda, 0x1b, 0x60, 0x97, 0xb0, 0x37, 0xa7,
	0xad, 0xcd, 0x29, 0x34, 0xbc, 0xe8, 0x0b, 0x4b, 0xb5, 0x3e, 0xab, 0xda, 0x9d, 0xf0, 0x43, 0x6b,
	0xd5, 0xd4, 0xd4, 0xf9, 0xfc, 0x9b, 0xc0, 0xa6, 0x7e, 0xc0, 0xc3, 0xec, 0x33, 0x0a, 0x90, 0x5e,
	0xab, 0xa8, 0xf8, 0x5b, 0x15, 0x95, 0x65, 0x9b, 0x38, 0x17, 0x46, 0xee, 0x1e, 0x2e, 0xe9, 0x54,
	0xcf, 0xb3, 0x15, 0xfa, 0x00, 0xdb, 0x23, 0xc1, 0x8b, 0x88, 0x4b, 0x21, 0xf3, 0xff, 0x79, 0xf5,
	0xc9, 0x19, 0xa1, 0xf7, 0xb0, 0x73, 0x83, 0xc5, 0xdc, 0xb0, 0xf4, 0xa0, 0xbc, 0xb6, 0x18, 0x57,
	0xf7, 0x68, 0x59, 0xeb, 0xd7, 0x72, 0xb8, 0xfb, 0xd2, 0xc6, 0xa9, 0xaf, 0x56, 0xc2, 0x0e, 0x44,
	0x62, 0x76, 0x66, 0xdc, 0xd2, 0x4b, 0x73, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0x80, 0x92, 0x5d,
	0xeb, 0x49, 0x02, 0x00, 0x00,
}
